version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - curl -fsSL https://bun.sh/install | bash
            - ~/.bun/bin/bun install --frozen-lockfile
    build:
        commands:
            - ~/.bun/bin/bun prisma generate
            - ~/.bun/bin/bun prisma migrate deploy
            - ~/.bun/bin/bun build
            - ~/.bun/bin/bun cleanup-console
    post_build:
        commands:
            - rm -rf node_modules
            - ~/.bun/bin/bun install -p --frozen-lockfile
            - echo Build completed on `date`
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
